[PHP]
memory_limit = 256M
upload_max_filesize = 32M
post_max_size = 32M
max_execution_time = 60
max_input_time = 60
default_charset = "UTF-8"
date.timezone = Asia/Baku
expose_php = Off

[Session]
session.cookie_httponly = 1
session.cookie_secure = 1
session.cookie_samesite = Strict
session.use_strict_mode = 1
session.use_only_cookies = 1

[Error Handling]
display_errors = Off
log_errors = On
error_log = /var/www/html/storage/logs/php-error.log
